### ISSUE TITLE
Reproducing Zhong et al., 2008

### ISSUE THREAD

**Issue by TobiasGlaubach** [empymod/empymod#102] opened 2020-07-15 07:42 UTC
Hi,
first of all thanks for the amazing library and all the work you put into making it!

### Description:
I am facing issues with oriented bipoles. 
I tried simulating a three layer system and all results are just `nan+nanj`

### Code to reproduce:
```python
#!/usr/bin/env python
# coding: utf-8

# In[1]:


import empymod
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('ggplot')


# In[2]:


# see: 
# https://empymod.readthedocs.io/en/stable/examples/frequency_domain/src_rec_comparison.html#sphx-glr-examples-frequency-domain-src-rec-comparison-py
# for explanation
map = {}
for i, (sc, vals) in enumerate(zip('xyz', [40, 50, 60])):
  for j, (rc, valr) in enumerate(zip('xyz', [4, 5, 6])):
    map['H_' + sc + rc] = (vals + valr, i, j)

map


# ## Paper with model
# 
# L. Zhong, J. Li, A. Bhardwaj, L. C. Shen and R. C. Liu, "Computation of Triaxial Induction Logging Tools in Layered Anisotropic Dipping Formations," in IEEE Transactions on Geoscience and Remote Sensing, vol. 46, no. 4, pp. 1148-1163, April 2008, doi: 10.1109/TGRS.2008.915749.

# In[3]:


name = 'Fig 3. with dip'   # Model name

sigma_h = np.r_[1, 0.55, 1]     # [S/m] Layer conductivities horizontal direction
sigma_v = np.r_[1, 0.18182, 1]  # [S/m] Layer conductivities vertical direction

depth = np.r_[5, 10] * 0.3048 # [m] Layer boundaries
aniso = sigma_v / sigma_h     # [ ] Layer anis. 
res = 1 / sigma_h             # [Ohm m] layer resistivity

# Modelling parameters
verb = 0

# Tool Parameters
freq = 20000        # [Hz] tool operation frequency
z_0 = 1             # [m] tool postition
L = 40 * (2.54/100) # [m] distance between source and receiver
azim = 0            # [°] horizontal deviation from x-axis, anti-clockwise
dip = 60             # [°] vertical deviation from xy-plane down/up-wards


# In[4]:


pdepth = np.repeat(np.r_[-1, depth], 2)
pdepth[:-1] = pdepth[1:]
pdepth[-1] = 2*depth[-1]
pres = np.repeat(res, 2)
pani = np.repeat(aniso, 2)

# Create figure
fig = plt.figure(figsize=(7, 5), facecolor='w')
fig.subplots_adjust(wspace=.25, hspace=.4)
plt.suptitle(name, fontsize=20)

# Plot Resistivities
ax1 = plt.subplot(1, 2, 1)
plt.plot(pres, pdepth, 'r')
plt.xscale('log')
plt.xlim([.2*np.array(res).min(), 2*np.array(res)[1:].max()])
plt.ylim([1.5*depth[-1], -1])
plt.ylabel('Depth (m)')
plt.xlabel(r'Resistivity $\rho_h\ (\Omega\,\rm{m})$')

# Plot anisotropies
ax2 = plt.subplot(1, 2, 2)
plt.plot(pani, pdepth, 'k')
# plt.xlim([0, 2])
plt.ylim([1.5*depth[-1], -1])
plt.xlabel(r'Anisotropy $\lambda (-)$')
ax2.yaxis.tick_right()

plt.show()


# In[5]:


results = np.zeros((3,3,20), dtype=np.complex)

for i_step, z_0 in enumerate(np.linspace(0, 5, 20)):
    print('==> Tool at z_0 = {:3.2}m'.format(z_0))
    # Spatial parameters
    p_src = [0, 0, z_0,     azim, dip]
    p_rec = [0, 0, z_0 - L, azim, dip]

    for comp, (ab, i_row, i_col) in map.items():


        inpdat = {'src': p_src, 
                  'rec': p_rec, 
                  'depth': depth,
                  'freqtime': freq, 
                  'aniso': aniso, 
                  'ab': ab,
                  'htarg': {
                      'pts_per_dec': -1
                      }, 
                  'verb': verb}

        # with the given inputs this should result in a infinitesimal 
        # small dipole instead of bipole (see https://empymod.readthedocs.io/en/stable/modeller.html)
        fEM = empymod.bipole(**inpdat, res=res)        
        results[i_row, i_col, i_step] = fEM
    print('H = ')
    print(results[:,:, i_step])
```

**Comment by prisae** [comment] 2020-07-15 08:08
Hi @TobiasGlaubach ,

I can only give you some hints here, I don't have the time right now to dig into it.

- Anisotropy is differently defined in empymod then what you use: `aniso=sqrt(rho_v/rho_h)`
- Please do use the verbosity (`verb`), it provides useful info.

Using `verb=3` yields me for your first model:
```
==> Tool at z_0 = 0.0m
* WARNING :: Unused **kwargs: {'ab': 44}.

:: empymod START  ::  v2.0.2

   depth       [m] :  1.524 3.048
   res     [Ohm.m] :  1 1.81818 1
   aniso       [-] :  1 0.330582 1
   epermH      [-] :  1 1 1
   epermV      [-] :  1 1 1
   mpermH      [-] :  1 1 1
   mpermV      [-] :  1 1 1
   direct field    :  Comp. in wavenumber domain
   frequency  [Hz] :  20000
   Hankel          :  DLF (Fast Hankel Transform)
     > Filter      :  Key 201 (2009)
     > DLF type    :  Lagged Convolution
   Loop over       :  Frequencies
   Source(s)       :  1 dipole(s)
     > x       [m] :  0
     > y       [m] :  0
     > z       [m] :  0
     > azimuth [°] :  0
     > dip     [°] :  60
   Receiver(s)     :  1 dipole(s)
     > x       [m] :  0
     > y       [m] :  0
     > z       [m] :  -1.016
     > azimuth [°] :  0
     > dip     [°] :  60
   Required ab's   :  11 13 31 33
* WARNING :: Offsets < 0.001 m are set to 0.001 m!

:: empymod END; runtime = 0:00:00.007082 :: 4 kernel call(s)
```

So I can see you want to model magnetic sources and receivers, but you actually model electric sources and receivers (`ab` is not a parameter in `bipole`, you have to use `msrc=True` and `mrec=True`, see the docstrings for more info, https://empymod.readthedocs.io/en/stable/modeller.html#empymod.model.bipole).

Also, 20,000 Hz is quite high, so I am not sure if these filters still work for that, or if you have to use other transform methods.

I hope that gives you some stuff to keep trying. Let me know how you get on.  The examples should give some a lot of info.

**Comment by prisae** [comment] 2020-07-15 08:48
Thinking about it I realize what is the problem: Source and receiver have to be horizontally separated. But your src and rec have both `x=y=0`, where the field is not defined (in the derivation). You can model the dipoles instead with multiple points (finite length) or, if you use loops, model it as a loop (see the loop examples in the gallery).

This is also why you get the warning (if `verb>0`):
```
* WARNING :: Offsets < 0.001 m are set to 0.001 m!
```

**Comment by TobiasGlaubach** [comment] 2020-07-15 09:25
Ok, thanks for the info and thinking about the issue. Also sorry for the inconvenience. I adjusted my code and nailed the issue down to source and receiver being on one Z axis. I will try loops now instead.

**Comment by prisae** [comment] 2020-07-15 09:28
No worries. Let me know how you get on!

**Comment by TobiasGlaubach** [comment] 2020-08-02 16:05
@prisae: So I have been working quite a bit more on it and also have been reading a lot in your documentation as well as source code. Thanks again for the quite well documented toolbox and making it completely open source.

I am trying to reproduce the results from https://doi.org/10.1109/TGRS.2008.915749 for the 60° dipped case. 
It is an anisotropic three layer system with a 60° dipped borehole containing a well logging tool. The well logging tool is modeled as three orthogonal dipole sources in X, Y, and Z  as well as three orthogonal receivers in X, Y, and Z which are about a meter further up in the borehole. Due to the borehole being dipped by 60° all sources and receivers are well separated in space.

By now I tried various things:
Sources and receivers:
- finite length loops as magnetic sources and magnetic receivers, 
- finite length bipoles as magnetic sources and magnetic receivers,
- infinitely small dipole point sources and receivers.

Integration:
- quadrature with extrapolation,
- quadrature,
- digital linear filters.

In the end I settled with the oriented dipoles and the DLF integration. I put quite some effort into getting the angles right and by now I am quite sure I got the coordinate systems and angles right. The results I get look quite realistic but do not match the results published in the paper. 

My implementation (as a minimal version for simplicity) is here on colab:
https://colab.research.google.com/drive/1I91cCIF7cLD4zET6toLHIaw7NcZ1JbrY?usp=sharing

What are your thoughts on the mismatch?

Thanks again.
Tobi

**Comment by prisae** [comment] 2020-08-02 19:54
Hi Tobi,

**First of all:** That looks like a very awesome project, please keep me posted!

**Second:** If you ever get it working I would be very happy to host your example in the gallery under [*Reproducing Published Results*](https://empymod.readthedocs.io/en/stable/examples/index.html#reproducing-published-results) - please consider it! You could either make a PR yourself or I can implement it and give attribution to you.

**Now, to your actual questions:** Unfortunate timing. Coming Wednesday I'll be off for two weeks on holiday, offline. And until then I am very busy, so I will not find the time to look at it.

However, I had a very quick glance and I wondered one thing: When they talk about, e.g., Hxx in the inclined case, is `x` then in the coordinate system of the model or in the coordinate system of the well? Because from my quick glance at your notebooks you use the coordinate system of the model. But I could imagine that they use the coordinate system of the inclined well. This could be a reason for the difference. In that case you would have to compose the x-field in the rotated coordinate system from the x/y/z fields in the model coordinate system.

If you do the vertical borehole (just keep a tiny horizontal offset), do the results also differ?

**Comment by prisae** [comment] 2020-08-02 19:55
(Oh, and as I said, I will be off. If you keep being stuck please just write me again. I will reply, it will just be in the second half of August.)

**Comment by TobiasGlaubach** [comment] 2020-08-03 07:30
@prisae : Thanks for the reply and no problem about not being able to help in the weeks to come.

**For keeping you posted:** 
sure thing! Glad to have someone elses input as well. Can we maybe reopen this "issue" as a WIP project and message board?

**For publishing as an example:**
Sure I am glad to give back and will prepare a script once we are reasonably sure we got it up and running.

**For horizontal well:**
I simulated this as well. Unfortunately the results differ as well, when I simulate a 0.1° dipped well:

![image](https://user-images.githubusercontent.com/34371519/89156718-6f13b180-d56b-11ea-932e-5af8614bbe01.png)

![image](https://user-images.githubusercontent.com/34371519/89156817-a2eed700-d56b-11ea-8daf-ca26907d4a5b.png)

I will continue working on it and keep you posted. Any ideas and input are highly appreciated.

Thanks and have a great vacation!
Tobias

**Comment by prisae** [comment] 2020-08-03 08:57
OK. I renamed the issue and open it again to keep track of it.

**Comment by prisae** [comment] 2020-08-03 09:07
In the two latest figures:

- Your imaginary part looks like -2\pi the real part of the paper
- Your real part looks like 2\pi the imaginary part of the paper

It looks like there is a factor `jw` difference or similar.

It your notebook, your using magnetic dipoles (which do not exist in reality) - do the authors use loops? That would explain the factor `jw`.

**Comment by TobiasGlaubach** [comment] 2020-08-04 10:23
Thanks for the `jw` hint, that is actually quite helpful.


According to Zhong et al., 2008 they modelled the system with magnetic dipoles.

"In the analysis, both the mandrel and the coil size will be neglected, and the actual coils will be replaced by point magnetic dipoles. The simulation code solves for all the nine components of the magnetic ﬁeld in a transverse anisotropic homogeneous layered medium."

Also when I use loops I get weird effects (spikes) on H_zz.
![image](https://user-images.githubusercontent.com/34371519/89282774-4fa08580-d64c-11ea-8934-87277e93a347.png)

I checked to see if that might be when `src `or `rec` is on a layer boundary but that is not the case (see the last plot in the notebook below):

Here is the notebook where I generated this plot:
https://colab.research.google.com/drive/17r4IJxoKlzZwU-qqJckeKhlAEmV6nVyR?usp=sharing

**Comment by prisae** [comment] 2020-08-04 11:04
`jw`-factor - could it be that you use an electric source instead of a magnetic source?

If they use magnetic dipoles, then you should be able to use `empymod.dipole` with the corresponding `ab`'s, e.g. `ab=66` for vertical source and receiver, see https://empymod.readthedocs.io/en/stable/modeller.html#empymod.model.dipole

![Selection_001](https://user-images.githubusercontent.com/8020943/89286718-ff78f180-d652-11ea-8544-9a01fecce644.png)

**Comment by TobiasGlaubach** [comment] 2020-08-04 11:07
So with the same weird ax scalings as used in the paper I found out:

- the papers real is approx `-pi/20 * imag(H...)` with my results
- the papers imag is approx `pi/20 * real(H...)` with my results
- there is a depth offset of about 1ft between my results and the papers results
- the paper has a 'nook' for the real part at approx 0ft, which is missing in my results

![image](https://user-images.githubusercontent.com/34371519/89286258-284cb700-d652-11ea-8c4a-612b10812d11.png)
![image](https://user-images.githubusercontent.com/34371519/89286449-84174000-d652-11ea-9139-055895917714.png)

**Comment by prisae** [comment] 2020-08-04 11:10
I see you use the loop function, with `mrec='loop'`, so it is a loop-loop setup.

Have you tried to use `empymod.dipole` instead, with the corresponding `ab`'s, e.g. `ab=66` for vertical source and receiver, see https://empymod.readthedocs.io/en/stable/modeller.html#empymod.model.dipole?

`dipole` is the simple-most implementation, and therefore a good starting point.

**Comment by prisae** [comment] 2020-08-04 11:11
(As they say they model magnetic point dipoles the `dipole`-routine should be perfect.)

**Comment by TobiasGlaubach** [comment] 2020-08-04 11:11
> `jw`-factor - could it be that you use an electric source instead of a magnetic source?
> 
> If they use magnetic dipoles, then you should be able to use `empymod.dipole` with the corresponding `ab`'s, e.g. `ab=66` for vertical source and receiver, see https://empymod.readthedocs.io/en/stable/modeller.html#empymod.model.dipole
> 
> ![Selection_001](https://user-images.githubusercontent.com/8020943/89286718-ff78f180-d652-11ea-8544-9a01fecce644.png)

I do the following:

```python
inpdat = {'src': psrc_znow, 
              'rec': prec_znow, 
              'depth': depth,
              'freqtime': freq, 
              'aniso': aniso, 
              'msrc': True, # source is magnetic
              'mrec': True, # receiver is magnetic
              'ht': 'dlf',
              'htarg': {
                  'pts_per_dec': -1
                  }, 
              'verb': verb}

    # with the given inputs this should result in a infinitesimal 
    # small dipole instead of bipole (see https://empymod.readthedocs.io/en/stable/modeller.html)
    fEM = empymod.bipole(**inpdat, res=res)
```

so I use both magnetic source and magnetic receiver. Btw. when I set `"msrc": False` I also get weird effects on the results.

I will try to simulate a vertical well now using `dipole` as you suggested lets see what this brings.

**Comment by prisae** [comment] 2020-08-04 11:25
(btw, you should be able to let the horizontal offset go to zero, it just can't be *exactly* zero..., But 1 mm horizontal offset, for instance, should be fine.)

**Comment by TobiasGlaubach** [comment] 2020-08-04 11:33
So when I use dipole with `ab=66 # mag_src_z -> mag_rec_z` I get the same result as I get with bipole and 0.1deg dipped well. So your two implementations are consistent :-)

![image](https://user-images.githubusercontent.com/34371519/89288958-c04c9f80-d656-11ea-80c7-cc583a2ff80d.png)

**Comment by prisae** [comment] 2020-08-04 11:38
:-D Well, under the hood, `bipole` and `loop` are just some fancier `dipole` routines, doing some integrations etc. But under the hood they all use the same kernel for point dipoles, so it has to be the same - otherwise we would indeed have some problems :-p

**Comment by TobiasGlaubach** [comment] 2020-08-04 11:47
As another benchmark a few days ago I simulated the same system (as isotropic) using SimPEG and compared it to your results:
Qualitatively the results looked similar (for the valid H_xx, H_yy, and H_zz cases), but quantitatively the values again differ.

![image](https://user-images.githubusercontent.com/34371519/89289878-40bfd000-d658-11ea-945a-5c1dfb11d248.png)
![image](https://user-images.githubusercontent.com/34371519/89289909-4ddcbf00-d658-11ea-98fd-cf8c30571c2c.png)

SimPEG model setup:

- 3 x magnetic dipole sources X,Y,and Z aligned
- 3 x H-field point receivers at cell centers
- Tensor-mesh with 1.5*skin depth as core size and some more coarse cells on the outside as padding
- All cells with `z<layer[i] and z >= layer[i+1]` get resistivity of layer i

**Comment by prisae** [comment] 2020-08-04 13:06
How did you define source and receiver with SimPEG?

**Comment by prisae** [comment] 2020-08-04 13:28
Regarding the "nooks": I would say that is bad numerical result in the published data. If you have a vertical well, axis-aligned sources and receiver, embedded in a horizontally stratified media, your responses *have to* be symmetric. The published results aren't. (Caution, I just judge from what I see and what you have told me, I have not read the article.)

**Comment by TobiasGlaubach** [comment] 2020-08-04 13:57
> How did you define source and receiver with SimPEG?
Like this:

```python

# coordinate system centered around transmitter
# reciever offset by L in tool direction 3D space
src_loc = np.r_[0, 0, 0]
rx_loc = src_loc + rot_tool.apply(np.r_[0., 0., L])

rxList = []
for majox_ax in 'xyz':
    rx_real = FDEM.Rx.Point_h(
        locs=rx_loc, orientation=majox_ax, component='real')

    rx_imag = FDEM.Rx.Point_h(
        locs=rx_loc, orientation=majox_ax, component='imag')
    rxList.append(rx_imag)
    rxList.append(rx_real)

srcList = []
for e_maj in np.eye(3):
    e_maj_d = rot_tool.apply(e_maj)
    e_maj_d = e_maj_d / np.linalg.norm(e_maj_d)
    
    if verbose:
        print(f'Source with orientation: {e_maj}')
        print(f'            ==> rotated: {e_maj_d}')
        
    src = FDEM.Src.MagDipole(
        rxList=rxList, 
        loc=src_loc,
        orientation=e_maj_d,
        freq=freq
    )
    srcList.append(src)
    
survey = FDEM.Survey(srcList)
```

the full script contains a lot of boilerplate code though

**Comment by TobiasGlaubach** [comment] 2020-08-04 14:01
> Regarding the "nooks": I would say that is bad numerical result in the published data. If you have a vertical well, axis-aligned sources and receiver, embedded in a horizontally stratified media, your responses _have to_ be symmetric. The published results aren't. (Caution, I just judge from what I see and what you have told me, I have not read the article.)

I (and the authors as well) am plotting magnetic-fluxes against well depth. So they have to be symmetrical, only if the layer model is symmetrical. Which according to what's shown in the paper should be the case. However they do not state, what's above 0ft height. So if they defined some different medium above 0 ft, there might be some difference there.

**Comment by prisae** [comment] 2020-08-04 14:41
> the full script contains a lot of boilerplate code though

Hm, yes, that looks good. I was interested in `FDEM.Rx.Point_h` and `FDEM.Src.MagDipole`, that looks OK.

>  against well depth

:smile: Good point! It is plotted against depth. Yes, then it could be anything if it is not stated. Having a quick look, they state "three layer" model, so it should be symmetric and the nook shouldn't be there, as the only boundaries are at 5 ft and 10 ft. But again, just guessing...

**Comment by prisae** [comment] 2020-08-04 14:51
- With SimPEG, do you use the `"EB"`-formulation or the `"HJ"`-formulation (defined in the source)?
- I would have to dig into it to see the exact formulation though - is the dipole actually a dipole, or is it a small loop? The difference is, again, a factor `jw`.

Anyway, I am off now. I'll check when I am back in two weeks if you succeeded or not. :crossed_fingers:

**Comment by TobiasGlaubach** [comment] 2020-08-30 09:35
> > Regarding the receivers. Checking the code it looks like they "simply" get the h-field component at receiver location by projecting the mesh field values to the receiver location.
> 
> Yes, and this through linear interpolation. If your receiver are at the corresponding edge then it will be precise, but if not there can be significant error due to (linear) interpolation.

Yes definitely, but over the simulation loop I vary the receiver and transmitter locations (by giving it a offset in Z), so it slowly changes it's position within a cell and at some offset will lay within a new cell. These discretization effects can be seen within the plots as the "sawtooth" pattern overlaying the curves. 

So yes there is a distortion, but the general curves should be alright, since (correct me please if I am mistaken) for a finite volume approach the flux values should be correct for the cases where a receiver is aligned exactly on a flux evaluation point (edge of the finite volume) and the interpolation error will get smaller the closer a receiver is to an edge.

**Comment by prisae** [comment] 2020-11-10 07:17
Hi @TobiasGlaubach ! Is this still an issue, or could you resolve it?

**Comment by TobiasGlaubach** [comment] 2020-11-17 08:49
Hi @prisae I am a bit lost with this, since I have three different answers from simpeg, empymod, and the (closed source) paper. But we were able to use empymod successfully for inversion modelling using numpy minimization functions and synthetic data. Tests with real data are outstanding. 

I will probably not continue on this since in order to find the reason for the different results between simpeg and empymod (and the paper as well) I would probably need to get a similar level of expertise as you and the authors of simpeg have, which is unrealistic for me at this time :-)

Feel free to proceed with this issue as you like, and thanks for all the help :-) and sorry for not being able to figure it out :-(

Keep up the good work and thank you very much for this awsome toolbox!

Tobi

**Comment by prisae** [comment] 2020-11-17 09:59
I am sorry to hear it didn't work out. Unfortunately it is more often than not impossible to reproduce published result which have been released without source code. That is why *reproducibility* is so important, and luckily is getting more attention in geophysics too. -- Did you ever reach out to the authors asking them about it?

I close this issue for now, feel free to re-open it any time if you start working on it again.

> But we were able to use empymod successfully for inversion modelling using numpy minimization functions and synthetic data. Tests with real data are outstanding.

If you have anything you can share I would love to see/read/hear more about this!

**Closed by prisae** 2020-11-17 09:59 UTC
Labels: question
